### ISSUE TITLE
can you put some of your favorite talylor swift song suggestions in the readme

### ISSUE THREAD

**Issue by animalphase** [teambekbek/BreakfastWithBekah#1]
![bitmoji](https://render.bitstrips.com/v2/cpanel/e99091d0-043e-4f09-af06-62a0d62eb583-356cc43a-5a91-4486-afdd-8cd00aac4371-v1.png?transparent=1&palette=1&width=246)

**Comment by animalphase** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/59381409-9870-4e8b-a755-838b81f933e7-356cc43a-5a91-4486-afdd-8cd00aac4371-v1.png?transparent=1&palette=1&width=246)

**Comment by teambekbek** [comment]
hi, 
i'd love to - will get on that immediately for you! 
<3 bekah

**Comment by animalphase** [comment]
thanks luv

![bitmoji](https://render.bitstrips.com/v2/cpanel/4cae9c64-d549-4bc5-a83f-45d72cbe5e4a-a1f7656c-7363-42fa-b360-3fde24d953bd-v1.png?transparent=1&palette=1&width=246)
